web/router.ex
defmodule ElixirChina.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
  end

  scope "/", ElixirChina do
    pipe_through :browser

    get "/", CategoryController, :index, as: :root
    get "/pages/:page", PageController, :show, as: :page

    # Posts and comments
    resources "/posts", PostController do
      resources "/comments", CommentController, except: [:index, :new, :show, :delete]
    end

    resources "/users", UserController do
      resources "/posts", PostController, only: [:index]
    end

    resources "/notifications", NotificationController, only: [:index, :delete]

    resources "/categories", CategoryController, only: [:index, :show]

    # Users
    get "/signup", UserController, :new

    # Sessions
    resources "/sessions", SessionController, only: [:new, :create]
    get "/signin", SessionController, :new
    get "/signout", SessionController, :delete

    # Other
    resources "/images", ImageController, only: [:create]
  end

  scope "/auth", ElixirChina do
    pipe_through :browser

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end
end

web/models/post.ex
defmodule ElixirChina.Post do
  use ElixirChina.Web, :model

  schema "posts" do
    field :title, :string
    field :content, :string

    timestamps type: Ecto.DateTime,
        inserted_at: :time,
         updated_at: :update_time

    belongs_to :user, ElixirChina.User
    belongs_to :category, ElixirChina.Category
    has_many :comments, ElixirChina.Comment
    field :comments_count, :integer, default: 0
  end

  @optional_fields ~w(update_time comments_count)a
  @required_fields ~w(content title category_id user_id)a
  @allowed_fields @required_fields ++ @optional_fields

  def changeset(post, params \\ %{}) do
    post
    |> cast(params, @allowed_fields)
    |> validate_required(@required_fields)
  end

  def count(query \\ __MODULE__) do
    from p in query, select: count(p.id)
  end

  def recent(query \\ __MODULE__) do
    from p in query, order_by: [desc: p.update_time]
  end

  def by_category_id(query \\ __MODULE__, category_id) do
    from p in query, where: p.category_id == ^category_id
  end

  def summary(post) do
    post.content
    # image
    |> String.replace(~r/\!\[.*?\]\(.*?\)/, "")
    # link
    |> String.replace(~r/\[(.*?)\]\(.*?\)/, "\\1")
    # leading formats
    |> String.replace(~r/(^|\n)(>\s*|#+\s*|\*\s+)/, "\\1")
    |> String.slice(0..99)
    |> String.trim
  end
end

web/controllers/post_controller.ex
defmodule ElixirChina.PostController do
  use ElixirChina.Web, :controller

  import ElixirChina.ControllerUtils
  alias ElixirChina.Router.Helpers
  alias ElixirChina.Post
  alias ElixirChina.Comment
  alias ElixirChina.Notification
  alias ElixirChina.Category
  alias ElixirChina.User

  def index(conn, %{"user_id" => user_id}) do
    render conn, "index.html",
          posts: Repo.all(from p in Post, where: p.user_id == ^String.to_integer(user_id), order_by: [{:desc, p.time}], preload: :category),
          user: Repo.get(User, String.to_integer(user_id)),
          user_id: get_session(conn, :user_id),
          conn: conn,
          pages: 0
  end

  def index(conn, _params) do
    redirect conn, to: "/"
  end

  def show(conn, %{"id" => id}) do
    case get_loaded_post(String.to_integer(id)) do
      post when is_map(post) ->
        user_id = get_session(conn, :user_id)
        comments = get_comments_with_loaded_user(String.to_integer(id))
        render conn, "show.html", post: post, comments: comments, user_id: user_id,
                                  is_admin: is_admin(user_id), page_title: post.title,
                                  page_summary: Post.summary(post)
      _ ->
        unauthorized conn
    end
  end

  def new(conn, _params) do
    render conn, "new.html", user_id: get_session(conn, :user_id), post: %Post{}, categories: Repo.all(Category), errors: nil
  end

  def create(conn, %{"post" => %{"title" => title, "content" => content, "category_id" => category_id}}) do
    user_id = get_user_id(conn)
    # utc = utc()
    # update_time is initialized here and will only be changed when a comment is to be made or deleted.
    post = %{title: title, content: content, user_id: user_id,
                category_id: String.to_integer(category_id), id: nil}

    changeset = Post.changeset(%Post{}, post)

    if changeset.valid? do
      if title =~ "毕业" do
        unauthorized conn
      else
        post = Repo.insert!(changeset)
        increment_score(Repo.get(User, user_id), 10)
        redirect conn, to: Helpers.post_path(conn, :show, post.id)
      end
    else
      render conn, "new.html", post: post, errors: changeset.errors, user_id: get_session(conn, :user_id), categories: Repo.all(Category)
    end
  end

  def edit(conn, %{"id" => id}) do
    post = validate_and_get_post(conn, id, false)
    case post do
      post when is_map(post) ->
        render conn, "edit.html", post: post, categories: Repo.all(Category), user_id: get_session(conn, :user_id)
      _ ->
        unauthorized conn
    end
  end

  def update(conn, %{"id" => id, "post" => params}) do
    post = validate_and_get_post(conn, id, false)
    update_params = %{title: params["title"],
                    content: params["content"],
                category_id: String.to_integer(params["category_id"])}

    changeset = Post.changeset(post, update_params)
    if changeset.valid? do
      Repo.update(changeset)
      json conn, %{location: Helpers.post_path(conn, :show, post.id)}
    else
      conn
      |> put_status(400)
      |> json(%{errors: flatten_changeset_errors(changeset)})
    end
  end

  def delete(conn, %{"id" => id}) do
    post = validate_and_get_post(conn, id, true)
    case post do
      post when is_map(post) ->
        (from n in Notification, where: n.post_id == ^String.to_integer(id)) |> Repo.delete_all
        (from comment in Comment, where: comment.post_id == ^String.to_integer(id)) |> Repo.delete_all
        increment_score(Repo.get(User, post.user_id), -10)
        Repo.delete(post)
        json conn, %{location: "/"}
      _ ->
        unauthorized conn
    end
  end

  defp get_loaded_post(id) do
    query = from(c in Post, where: c.id == ^id, preload: [:user, :category])
    Repo.one(query)
  end

  defp get_comments_with_loaded_user(id) do
    query = from(c in Comment, where: c.post_id == ^id, order_by: c.time, preload: :user)
    Repo.all(query)
  end

  # Admin is only allowed to delete, but not edit, a post
  defp validate_and_get_post(conn, id, admin_ok) do
    user_id = get_user_id(conn)
    post = get_loaded_post(id)
    if user_id == post.user_id or (admin_ok and is_admin(user_id)) do
      post
    else
      unauthorized conn
    end
  end

  defp is_admin(user_id) do
    unless is_nil(user_id) do
      user = Repo.one(from u in User, where: u.id == ^user_id)
      is_map(user) and user.admin
    end
  end
end

web/views/post_view.ex
defmodule ElixirChina.PostView do
  use ElixirChina.Web, :view

  def datetime_string(datetime) do
    Ecto.DateTime.to_iso8601(datetime)
  end
end

web/templates/post/_form.html.eex
<form action="<%= @action %>" method="post">
  <input type="hidden" name="_method" value="POST">
  <div class="form-group form-inline">
    <label class="">所属板块
      <select name="post[category_id]" class="form-control" value="<%= @post.category_id %>">
        <%= for category <- @categories do %>
          <option value="<%= category.id %>" <%= if @post.id && @post.category.id == category.id, do: "selected" %>><%= category.name %></option>
        <% end %>
      </select>
    </label>
  </div>
  <div class="form-group">
    <input type="text" class="form-control" name="post[title]" placeholder="请输入标题" value="<%= @post.title %>">
  </div>
  <div class="form-group">
    <textarea name="post[content]" class="editor" id="editor"><%= @post.content %></textarea>
  </div>
  <div class="form-group">
    <input type="submit" class="btn btn-primary" value="<%= @post.id && "更新" || "发布" %>"></input>
  </div>

  <%= if @errors do %>
    <%= for {key, error} <- @errors do %>
      <div class="alert alert-warning">
        <%= "#{key} #{elem(error, 0)}" %>
      </div>
    <% end %>
  <% end %>
</form>

web/templates/post/edit.html.eex
<div class="panel panel-default">
  <div class="panel-heading">修改话题</div>
  <div class="panel-body post">
    <%= render ElixirChina.PostView, "_form.html", action: post_path(@conn, :update, @post.id), post: @post, categories: @categories, errors: nil %>
  </div>
</div>

<script>
  $("form").on("submit", function(event) {
    event.preventDefault();

    $that = this;
    Editor.editor.element.textContent = Editor.editor.value();

    $.ajax({
      url: $that.getAttribute('action'),
      type: "PATCH",
      data: $('form').serialize(),
      success: function(data) {
        window.location = data.location;
      }
    });
  });
</script>

web/templates/post/feed.xml.eex
<?xml version="1.0" encoding="utf-8" ?>
<rss version="2.0" xmlns:wfw="http://wellformedweb.org/CommentAPI/">
  <channel>
    <title>Elixir China社区</title>
    <link>http://elixir-cn.com/</link>
    <description>最新发帖</description>
    <language>en-us</language>
    <%= for post <- @posts do %>
      <item>
        <title><%= post.title %></title>
        <link><%= post_url(@conn, :show, post.id) %></link>
        <author><%= post.user.name %></author>
        <pubDate><%= Ecto.DateTime.to_iso8601(post.time) %></pubDate>
        <description><%= post.content %></description>
      </item>
    <% end %>
  </channel>
</rss>

web/templates/post/index.html.eex
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @user.name %>的帖子
  </div>
  <%= render ElixirChina.SharedView, "_topic_list.html", posts: @posts, user: @user, conn: @conn, pages: 0 %>
</div>

web/templates/post/new.html.eex
<div class="panel panel-default">
  <div class="panel-heading">发表话题</div>
  <div class="panel-body post">
    <%= render ElixirChina.PostView, "_form.html", action: "/posts", post: @post, categories: @categories, errors: @errors, method: "POST"%>
  </div>
</div>

web/templates/post/show.html.eex
<article class="panel panel-default topic">
  <header class="panel-heading" style=" display: block;height: 80px">

    <div class="media-left" style="float: left">
      <h3 class="panel-title">
        <div class="title"><%= @post.title %></div>
      </h3>
      <h6>
          作者 <a href="<%= user_path(@conn, :show, @post.user_id) %>"><%= @post.user.name %></a>
          所属板块 <a href="<%= category_path(@conn, :show, @post.category_id) %>" target="_blank">
                    <mark class="text-muted"><%= @post.category.name %></mark>
                  </a>
          创建于
                  <time class="last_active_time pubdate" datetime="<%= datetime_string @post.update_time %>">
              </time>
      </h6>
    </div>
    <div class="media-right" style="float: right; padding: 10px">
      <a class="user_avatar" href="<%= user_path(@conn, :show, @post.user_id) %>">
        <img src="<%= avatar_url(@post.user && @post.user.email || @post.user.email) %>" height="48" width="48" class="img-rounded">
      </a>
    </div>
  </header>
  <div class="clear"> </div>

  <div class="panel-body">
    <div class="markdown-text"><%= @post.content %></div>
  </div>

  <%= if @user_id == @post.user_id or @is_admin do %>
    <div class="panel-footer">
      <form action="/posts/<%= @post.id %>" id="delete-form" method="post">
        <%= if @user_id == @post.user_id do %>
          <a href="<%= post_path(@conn, :edit, @post.id) %>" class="btn btn-primary">
            编辑
          </a>
        <% end %>
        <input type="submit" class="btn btn-danger" value="删除"></input>
      </form>
    </div>
  <% end %>
</article>

<div class="panel panel-default comments">
  <header class="panel-heading">
    <%=length(@comments)%> 回复
  </header>

  <%= if @comments != nil do %>
    <ul class="comment_list list-group">
    <%= for comment <- @comments do %>
      <li class="list-group-item media">
        <div class="media-left">
          <a href="<%= user_path(@conn, :show, comment.user_id) %>" class="user_avatar">
            <img src="<%= avatar_url(comment.user.email)%>" height="48" width="48" class="img-rounded">
          </a>
        </div>
        <div class="media-body reply_content">
          <h6 class="media-heading">
            <a class="reply_author" href="<%= user_path(@conn, :show, comment.user_id) %>">
              <%= comment.user.name %>
            </a>
            <small class="media-heading">
              于 <time class="reply_time pubdate" datetime="<%= to_string comment.time %>">
                <%= to_string comment.time %>
              </time> 发表
            </small>
            <span class="pull-right">
              <%= if @user_id != nil do %>
                <%= if @user_id == comment.user_id do %>
                  <a href="<%= post_comment_path(@conn, :edit, @post.id, comment.id) %>" class="reply_author">
                    修改
                  </a>
                <% end %>
                <a href="#post-form" data-uid="<%= comment.user.id %>" data-uname="<%= comment.user.name %>" class="reply_author reply-link">
                  回复
                </a>
              <% end %>
            </span>
          </h6>
          <div class="markdown-text"><%= comment.content %></div>
        </div>
      </li>
    <% end %>
    </ul>
  <% end %>
</div>

<%= if @user_id != nil do %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <span class="col_fade">回帖</span>
    </div>
    <div class="panel-body reply">
      <form action="<%= post_comment_path(@conn, :create, @post.id)%>" id="post-form" method="post">
          <input type="hidden" id="comment-uid" name="comment[uid]" value="">
          <textarea rows="8" name="comment[content]" class="editor" id="editor"></textarea>
          <div class="editor_buttons">
            <input type="submit" class="btn btn-primary" value="回复"></input>
          </div>
      </form>
    </div>
  </div>
<% end %>

<script>
  $("#delete-form").on("submit", function(event) {
    event.preventDefault();

    $that = this;

    $.ajax({
      url: $that.getAttribute('action'),
      type: "DELETE",
      data: $('form').serialize(),
      success: function(data) {
        window.location = data.location;
      }
    });
  });
</script>