web/router.ex
defmodule ElixirChina.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
  end

  scope "/", ElixirChina do
    pipe_through :browser

    get "/", CategoryController, :index, as: :root
    get "/pages/:page", PageController, :show, as: :page

    # Posts and comments
    resources "/posts", PostController do
      resources "/comments", CommentController, except: [:index, :new, :show, :delete]
    end

    resources "/users", UserController do
      resources "/posts", PostController, only: [:index]
    end

    resources "/notifications", NotificationController, only: [:index, :delete]

    resources "/categories", CategoryController, only: [:index, :show]

    # Users
    get "/signup", UserController, :new

    # Sessions
    resources "/sessions", SessionController, only: [:new, :create]
    get "/signin", SessionController, :new
    get "/signout", SessionController, :delete

    # Other
    resources "/images", ImageController, only: [:create]
  end

  scope "/auth", ElixirChina do
    pipe_through :browser

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end
end

web/views/layout_view.ex
defmodule ElixirChina.LayoutView do
  use ElixirChina.Web, :view

  @title "ElixirChina"
  @summary "ElixirChina 是中国人学习和交流 Elixir 语言的乐园。"

  def show_statics?(conn) do
    Dict.get(conn.assigns, :show_statics)
  end

  def show_social_login?(conn) do
    Map.get(conn.assigns, :show_social_login)
  end

  def page_title(assigns) do
    if assigns[:page_title] do
      assigns[:page_title] <> " - " <> @title
    else
      @title
    end
  end

  def page_summary(assigns) do
    if assigns[:page_summary], do: assigns[:page_summary], else: @summary
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="zh_CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<%= page_summary(assigns) %>">
    <meta name="author" content="">
    <meta name="og:site_name" content="ElixirChina">
    <meta name="og:title" content="<%= assigns[:page_title] %>">
    <meta name="og:description" content="<%= assigns[:page_summary] %>">
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:site" content="@elixirchina" />
    <meta name="twitter:title" content="<%= assigns[:page_title] %>" />
    <meta name="twitter:description" content="<%= page_summary(assigns) %>" />

    <title><%= page_title(assigns) %></title>
    <link rel="icon" type="image/x-icon" href="/img/favicon.ico">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/fontawesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/css/app.css">
    <script src="//cdn.jsdelivr.net/jquery/2.2.4/jquery.min.js"></script>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <script src="//cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/marked.js"></script>
    <script type="text/javascript" src="/js/pagination.js"></script>
    <script type="text/javascript" src="/js/inline-attachment.min.js"></script>
    <script type="text/javascript" src="/js/codemirror-4.inline-attachment.min.js"></script>
    <script type="text/javascript" src="/js/helper.js"></script>
    <script type="text/javascript" src="/js/app.js"></script>
    <%= render ElixirChina.SharedView, "_google_analytics.html", [] %>
  </head>

  <body>
    <%= render ElixirChina.SharedView, "_nav.html", conn: @conn, user_id: @user_id %>
    <div class="container">
      <div class="col-md-9" role="main">
        <%= render @view_module, @view_template, assigns %>
      </div>
      <sidebar class="col-md-3" role="sidebar">
        <%= if show_social_login?(@conn) do %>
          <%= render ElixirChina.SharedView, "_social_login.html", conn: @conn %>
        <% end %>
        <%= if show_statics?(@conn) do %>
          <%= render ElixirChina.SharedView, "_leading_board.html", conn: @conn, leading_users: @leading_users %>
          <%= render ElixirChina.SharedView, "_statics.html", post_count: @post_count, comment_count: @comment_count, user_count: @user_count %>
        <% end %>
        <%= render ElixirChina.SharedView, "_contrib.html", [] %>
        <%= render ElixirChina.SharedView, "_friend_community.html", conn: @conn %>
      </sidebar>

    </div>

    <div class="footer">
      <div class="container">
        <div class="text-muted">
          Made with &#9825; by Elixir makers.
        </div>
      </div>
    </div>
  </body>
</html>

web/templates/layout/application.html.eex
<!DOCTYPE html>
<html lang="zh_CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="ElixirChina(ElixirCN)是中国人学习和交流Elixir语言的乐园。">
    <meta name="author" content="">

    <title>ElixirChina</title>
    <link rel="icon" type="image/x-icon" href="/img/favicon.ico">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="/css/app.css">
    <link rel="stylesheet" href="/css/editor.css" />
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/editor.js"></script>
    <script type="text/javascript" src="/js/marked.js"></script>
    <script type="text/javascript" src="/js/pagination.js"></script>
    <script type="text/javascript" src="/js/helper.js"></script>
    <script type="text/javascript" src="/js/app.js"></script>
    <%= render ElixirChina.SharedView, "_google_analytics.html", [] %>
  </head>

  <body>
    <%= render ElixirChina.SharedView, "_nav.html", user_id: @user_id %>
    <div class="container">
      <div class="col-md-9" role="main">
        <%= @inner %>
      </div>
      <sidebar class="col-md-3" role="sidebar">
        <%= render ElixirChina.SharedView, "_leading_board.html", leading_users: @leading_users %>
        <%= render ElixirChina.SharedView, "_statics.html", post_count: @post_count, comment_count: @comment_count, user_count: @user_count %>
        <%= render ElixirChina.SharedView, "_contrib.html", [] %>
        <%= render ElixirChina.SharedView, "_friend_community.html", [] %>
      </sidebar>

    </div>

    <div id="footer">
      <div class="container">
        <div class="text-muted">
          Made with &#9825; by Elixir makers.
        </div>
      </div>
    </div>
  </body>
</html>

web/templates/layout/nav.html.eex
<div class='navbar'>
  <div class='navbar-inner'>
    <div class="container">
      <ul class="nav">
        <li><a class="brand" href="/"> ElixirChina </a></li>
      </ul>

      <ul class="nav pull-right">
        <li><a href="<%= root_path(:index) %>"> 主页 </a></li>
        
        <%= if @user_id == nil do %>
          <li><a href="/signup"> 注册 </a></li>
          <li><a href="/signin"> 登录 </a></li>
        <% end %>

        <%= if @user_id != nil do %>
          <li><a href="/signout"> 退出 </a></li>
          <li><a href="<%= user_path(:show, @user_id) %>"> 账户 </a></li>
          <li><a href="<%= user_notification_path(:index, @user_id) %>"> 消息中心 </a></li>
          <li><a href="<%= user_post_path(:index, @user_id) %>"> 我的帖子 </a></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>