web/router.ex
defmodule ElixirChina.Router do
  use Phoenix.Router

  pipeline :browser do
    plug :accepts, ~w(html)
    plug :fetch_session
  end

  scope "/", ElixirChina do
    pipe_through :browser

    get "/", CategoryController, :index, as: :root
    get "/pages/:page", PageController, :show, as: :page

    # Posts and comments
    resources "/posts", PostController do
      resources "/comments", CommentController, except: [:index, :new, :show, :delete]
    end

    resources "/users", UserController do
      resources "/posts", PostController, only: [:index]
    end

    resources "/notifications", NotificationController, only: [:index, :delete]

    resources "/categories", CategoryController, only: [:index, :show]

    # Users
    get "/signup", UserController, :new

    # Sessions
    resources "/sessions", SessionController, only: [:new, :create]
    get "/signin", SessionController, :new
    get "/signout", SessionController, :delete

    # Other
    resources "/images", ImageController, only: [:create]
  end

  scope "/auth", ElixirChina do
    pipe_through :browser

    get "/:provider", AuthController, :index
    get "/:provider/callback", AuthController, :callback
  end
end

web/views/shared_view.ex
defmodule ElixirChina.SharedView do
  use ElixirChina.Web, :view

  def datetime_string(datetime) do
    Ecto.DateTime.to_iso8601(datetime)
  end
end

web/templates/shared/_contrib.html.eex
<div class="panel panel-default">
  <div class="panel-heading">
    贡献代码
  </div>
  <div class="panel-body">
    <a href="https://github.com/elixir-cn/elixir-china" target="_blank">请点击这里</a>
  </div>
</div>

web/templates/shared/_friend_community.html.eex
<div class="panel panel-default">
  <div class="panel-heading">
    友情社区
  </div>
  <div class="panel-body friendship-community">
    <a href="https://ruby-china.org/" target="_blank">
      <img src="<%= static_path(@conn, "/images/friend-community/ruby-china.png") %>" class="community-brand">
    </a>
    <a href="http://golangtc.com/" target="_blank">
      <img src="<%= static_path(@conn, "/images/friend-community/golang-china.png") %>" class="community-brand">
    </a>
    <a href="https://phphub.org/" target="_blank">
      <img src="<%= static_path(@conn, "/images/friend-community/phphub.png") %>" class="community-brand">
    </a>
  </div>
</div>

web/templates/shared/_google_analytics.html.eex
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-58427657-1', 'auto');
  ga('send', 'pageview');

</script>

web/templates/shared/_leading_board.html.eex
<%= if @leading_users != nil do %>
  <div class="panel panel-default">
    <div class="panel-heading">
      积分榜
    </div>
    <div class="panel-body">
      <ol class="list-unstyled">
        <%= for user <- @leading_users do %>
          <li>
            <span class="top_score"><%= user.score %></span>
            <span class="user_name">
              <a href="<%= user_path(@conn, :show, user.id) %>">
                <%= user.name %>
              </a>
            </span>
          </li>
        <% end %>
      </ol>
    </div>
  </div>
<% end %>

web/templates/shared/_nav.html.eex
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ElixirChina</a>
    </div>

    <div class="collapse navbar-collapse" id="navbar-collapse">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="<%= root_path(@conn, :index) %>"> 主页 </a></li>

        <%= if @user_id == nil do %>
          <li><a href="/signup"> 注册 </a></li>
          <li><a href="/signin"> 登录 </a></li>
        <% end %>

        <%= if @user_id != nil do %>
          <li><a href="/signout"> 退出 </a></li>
          <li><a href="<%= user_path(@conn, :show, @user_id) %>"> 账户 </a></li>
          <li><a href="<%= notification_path(@conn, :index) %>"> 消息中心 </a></li>
          <li><a href="<%= user_post_path(@conn, :index, @user_id) %>"> 我的帖子 </a></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

web/templates/shared/_social_login.html.eex
<div class="panel panel-default">
  <div class="panel-heading">
    用其他平台的帐号登录
  </div>
  <div class="panel-body friendship-community">
    <a href="<%= auth_path(@conn, :index, :github) %>" class="btn btn-default btn-md">
      <i class='fa fa-github'></i> Github
    </a>
  </div>
</div>

web/templates/shared/_statics.html.eex
<%= if @post_count != nil and @comment_count != nil and @user_count != nil do %>
  <div class="panel panel-default">
    <div class="panel-heading">
      社区状态
    </div>
    <div class="panel-body">
      <ul class="list-unstyled">
        <li>会员 <%= @user_count %></li>
        <li>主题 <%= @post_count %></li>
        <li>回复 <%= @comment_count %></li>
      </ul>
    </div>
  </div>
<% end %>

web/templates/shared/_topic_list.html.eex
<ul class="topic_list list-group">
  <%= for post <- @posts do %>
    <li class="list-group-item media">
      <div class="media-left">
        <a class="user_avatar" href="<%= user_path(@conn, :show, post.user_id) %>">
          <img src="<%= avatar_url(@user && @user.email || post.user.email) %>" height="48" width="48" class="img-rounded">
        </a>
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <a href="<%= post_path(@conn, :show, post.id) %>" style="color: #000">
            <%= post.title %>
          </a>
        </h4>
        <h4 class="media-heading">
          <a href="<%= category_path(@conn, :show, post.category_id) %>">
          <mark class="text-muted"><%= post.category.name %></mark></a>
          <small>
            <a href="<%= user_path(@conn, :show, post.user_id) %>" class="author">
              <%= @user && @user.name || post.user.name %>
            </a>
            的帖子于
            <time class="last_active_time pubdate" datetime="<%= datetime_string post.update_time %>">
            </time>
            最后更新</small>
        </h4>
      </div>
      <div class="media-right">
        <h4><div class="label label-<%= if post.comments_count > 0, do: "primary", else: "default" %>"><%= post.comments_count %></div></h4>
      </div>
    </li>
  <% end %>
  <%= if (@pages || 0) > 1 do %>
    <li class="topics_pagination list-group-item" data-pages="<%= @pages %>" data-page="<%= @page %>"></li>
  <% end %>
</ul>